cams:
  default_year: 2019
  files:
    2019: INPUT/Emissions/CAMS-REG-v8_1_emissions_year2019.nc
    2021: INPUT/Emissions/CAMS-REG-v8_1_emissions_year2021.nc

Sector_specific : 
    A_PublicPower:
        config: proxy/config/sector/A_PublicPower/A_PublicPower_sector_config.yaml
        output_folder : INPUT/Proxy_weights/A_PublicPower
        pipeline: proxy/sector/A_PublicPower/pipeline.py
    B_Industry:
        config: proxy/config/sector/B_Industry/B_Industry_sector_config.yaml
        output_folder : INPUT/Proxy_weights/B_Industry
        pipeline: proxy/sector/B_Industry/pipeline.py
    C_Othercombustion:
        config: proxy/config/sector/C_Othercombustion/C_Othercombustion_sector_config.yaml
        output_folder : INPUT/Proxy_weights/C_Othercombustion
        pipeline: proxy/sector/C_Othercombustion/pipeline.py
    D_Fugitive:
        config: proxy/config/sector/D_Fugitive/D_Fugitive_sector_config.yaml
        output_folder : INPUT/Proxy_weights/D_Fugitive
        pipeline: proxy/sector/D_Fugitive/pipeline.py
    E_Solvents:
        config: proxy/config/sector/E_Solvents/E_Solvents_sector_config.yaml
        output_folder : INPUT/Proxy_weights/E_Solvents
        pipeline: proxy/sector/E_Solvents/pipeline.py
    F_Roads:
        config: proxy/config/sector/F_Roads/F_Roads_sector_config.yaml
        output_folder : INPUT/Proxy_weights/F_Roads
        pipeline: proxy/sector/F_Roads/pipeline.py
    G_Shipping:
        config: proxy/config/sector/G_Shipping/G_Shipping_sector_config.yaml
        output_folder : INPUT/Proxy_weights/G_Shipping
        pipeline: proxy/sector/G_Shipping/pipeline.py
    H_Aviation:
        config: proxy/config/sector/H_Aviation/H_Aviation_sector_config.yaml
        output_folder : INPUT/Proxy_weights/H_Aviation
        pipeline: proxy/sector/H_Aviation/pipeline.py
    I_Offroad:
        config: proxy/config/sector/I_Offroad/I_Offroad_sector_config.yaml
        output_folder : INPUT/Proxy_weights/I_Offroad
        pipeline: proxy/sector/I_Offroad/pipeline.py
    J_Waste:
        config: proxy/config/sector/J_Waste/J_Waste_sector_config.yaml
        output_folder : INPUT/Proxy_weights/J_Waste
        pipeline: proxy/sector/J_Waste/pipeline.py
    K_Agriculture:
        config: proxy/config/sector/K_Agriculture/K_Agriculture_sector_config.yaml
        output_folder : INPUT/Proxy_weights/K_Agriculture
        pipeline: proxy/sector/K_Agriculture/pipeline.py


   