emep_fuel_hints:
- gains_fuel_contains: Natural gas
  emep_fuel_contains: Natural gas
- gains_fuel_contains: Gas oil
  emep_fuel_contains: Gas oil
- gains_fuel_contains: LPG
  emep_fuel_contains: Natural gas
- gains_fuel_contains: Brown coal
  emep_fuel_contains: Coal fuels
- gains_fuel_contains: Hard coal
  emep_fuel_contains: Coal fuels
- gains_fuel_contains: Derived coal
  emep_fuel_contains: Coal fuels
- gains_fuel_contains: lignite
  emep_fuel_contains: Coal fuels
- gains_fuel_contains: Biogas
  emep_fuel_contains: Natural gas
rules:
- appliance_contains_all:
  - Cooking stoves
  - (households)
  class: R_COOKING_STOVE
  fuel_contains: Natural gas
- appliance_contains_all:
  - Cooking stoves
  - (agr, forestry, other)
  class: R_COOKING_STOVE
  fuel_contains: Natural gas
- appliance_contains_all:
  - Fireplaces
  - (households)
  class: R_FIREPLACE
  fuel_contains: Natural gas
- appliance_contains_all:
  - Fireplaces
  - (agr, forestry, other)
  class: R_FIREPLACE
  fuel_contains: Natural gas
- appliance_contains_all:
  - Heating stoves
  - (households)
  class: R_HEATING_STOVE
  fuel_contains: Natural gas
- appliance_contains_all:
  - Heating stoves
  - (agr, forestry, other)
  class: R_HEATING_STOVE
  fuel_contains: Natural gas
- appliance_contains_all:
  - Three-stone stove
  class: R_COOKING_STOVE
  fuel_contains: Natural gas
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (households)
  class: R_BOILER_AUT
  fuel_contains: Natural gas
- appliance_contains_all:
  - Single house boilers
  - manual
  - (households)
  class: R_BOILER_MAN
  fuel_contains: Natural gas
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
  fuel_contains: Natural gas
- appliance_contains_all:
  - Single house boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
  fuel_contains: Natural gas
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (commercial)
  class: C_BOILER_AUT
  fuel_contains: Natural gas
- appliance_contains_all:
  - Medium boilers
  - manual
  - (commercial)
  class: C_BOILER_MAN
  fuel_contains: Natural gas
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
  fuel_contains: Natural gas
- appliance_contains_all:
  - Medium boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
  fuel_contains: Natural gas
- appliance_contains_all:
  - Cooking stoves
  - (households)
  class: R_COOKING_STOVE
  fuel_contains: Gas oil
- appliance_contains_all:
  - Cooking stoves
  - (agr, forestry, other)
  class: R_COOKING_STOVE
  fuel_contains: Gas oil
- appliance_contains_all:
  - Fireplaces
  - (households)
  class: R_FIREPLACE
  fuel_contains: Gas oil
- appliance_contains_all:
  - Fireplaces
  - (agr, forestry, other)
  class: R_FIREPLACE
  fuel_contains: Gas oil
- appliance_contains_all:
  - Heating stoves
  - (households)
  class: R_HEATING_STOVE
  fuel_contains: Gas oil
- appliance_contains_all:
  - Heating stoves
  - (agr, forestry, other)
  class: R_HEATING_STOVE
  fuel_contains: Gas oil
- appliance_contains_all:
  - Three-stone stove
  class: R_COOKING_STOVE
  fuel_contains: Gas oil
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (households)
  class: R_BOILER_AUT
  fuel_contains: Gas oil
- appliance_contains_all:
  - Single house boilers
  - manual
  - (households)
  class: R_BOILER_MAN
  fuel_contains: Gas oil
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
  fuel_contains: Gas oil
- appliance_contains_all:
  - Single house boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
  fuel_contains: Gas oil
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (commercial)
  class: C_BOILER_AUT
  fuel_contains: Gas oil
- appliance_contains_all:
  - Medium boilers
  - manual
  - (commercial)
  class: C_BOILER_MAN
  fuel_contains: Gas oil
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
  fuel_contains: Gas oil
- appliance_contains_all:
  - Medium boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
  fuel_contains: Gas oil
- appliance_contains_all:
  - Cooking stoves
  - (households)
  class: R_COOKING_STOVE
  fuel_contains: coal
- appliance_contains_all:
  - Cooking stoves
  - (agr, forestry, other)
  class: R_COOKING_STOVE
  fuel_contains: coal
- appliance_contains_all:
  - Fireplaces
  - (households)
  class: R_FIREPLACE
  fuel_contains: coal
- appliance_contains_all:
  - Fireplaces
  - (agr, forestry, other)
  class: R_FIREPLACE
  fuel_contains: coal
- appliance_contains_all:
  - Heating stoves
  - (households)
  class: R_HEATING_STOVE
  fuel_contains: coal
- appliance_contains_all:
  - Heating stoves
  - (agr, forestry, other)
  class: R_HEATING_STOVE
  fuel_contains: coal
- appliance_contains_all:
  - Three-stone stove
  class: R_COOKING_STOVE
  fuel_contains: coal
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (households)
  class: R_BOILER_AUT
  fuel_contains: coal
- appliance_contains_all:
  - Single house boilers
  - manual
  - (households)
  class: R_BOILER_MAN
  fuel_contains: coal
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
  fuel_contains: coal
- appliance_contains_all:
  - Single house boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
  fuel_contains: coal
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (commercial)
  class: C_BOILER_AUT
  fuel_contains: coal
- appliance_contains_all:
  - Medium boilers
  - manual
  - (commercial)
  class: C_BOILER_MAN
  fuel_contains: coal
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
  fuel_contains: coal
- appliance_contains_all:
  - Medium boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
  fuel_contains: coal
- appliance_contains_all:
  - Cooking stoves
  - (households)
  class: R_COOKING_STOVE
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Cooking stoves
  - (agr, forestry, other)
  class: R_COOKING_STOVE
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Fireplaces
  - (households)
  class: R_FIREPLACE
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Fireplaces
  - (agr, forestry, other)
  class: R_FIREPLACE
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Heating stoves
  - (households)
  class: R_HEATING_STOVE
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Heating stoves
  - (agr, forestry, other)
  class: R_HEATING_STOVE
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Three-stone stove
  class: R_COOKING_STOVE
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (households)
  class: R_BOILER_AUT
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Single house boilers
  - manual
  - (households)
  class: R_BOILER_MAN
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Single house boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (commercial)
  class: C_BOILER_AUT
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Medium boilers
  - manual
  - (commercial)
  class: C_BOILER_MAN
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Medium boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
  fuel_contains: Fuelwood
- appliance_contains_all:
  - Cooking stoves
  - (households)
  class: R_COOKING_STOVE
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Cooking stoves
  - (agr, forestry, other)
  class: R_COOKING_STOVE
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Fireplaces
  - (households)
  class: R_FIREPLACE
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Fireplaces
  - (agr, forestry, other)
  class: R_FIREPLACE
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Heating stoves
  - (households)
  class: R_HEATING_STOVE
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Heating stoves
  - (agr, forestry, other)
  class: R_HEATING_STOVE
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Three-stone stove
  class: R_COOKING_STOVE
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (households)
  class: R_BOILER_AUT
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Single house boilers
  - manual
  - (households)
  class: R_BOILER_MAN
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Single house boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (commercial)
  class: C_BOILER_AUT
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Medium boilers
  - manual
  - (commercial)
  class: C_BOILER_MAN
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Medium boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
  fuel_contains: Agricultural residues
- appliance_contains_all:
  - Cooking stoves
  - (households)
  class: R_COOKING_STOVE
  fuel_contains: Dung
- appliance_contains_all:
  - Cooking stoves
  - (agr, forestry, other)
  class: R_COOKING_STOVE
  fuel_contains: Dung
- appliance_contains_all:
  - Fireplaces
  - (households)
  class: R_FIREPLACE
  fuel_contains: Dung
- appliance_contains_all:
  - Fireplaces
  - (agr, forestry, other)
  class: R_FIREPLACE
  fuel_contains: Dung
- appliance_contains_all:
  - Heating stoves
  - (households)
  class: R_HEATING_STOVE
  fuel_contains: Dung
- appliance_contains_all:
  - Heating stoves
  - (agr, forestry, other)
  class: R_HEATING_STOVE
  fuel_contains: Dung
- appliance_contains_all:
  - Three-stone stove
  class: R_COOKING_STOVE
  fuel_contains: Dung
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (households)
  class: R_BOILER_AUT
  fuel_contains: Dung
- appliance_contains_all:
  - Single house boilers
  - manual
  - (households)
  class: R_BOILER_MAN
  fuel_contains: Dung
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
  fuel_contains: Dung
- appliance_contains_all:
  - Single house boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
  fuel_contains: Dung
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (commercial)
  class: C_BOILER_AUT
  fuel_contains: Dung
- appliance_contains_all:
  - Medium boilers
  - manual
  - (commercial)
  class: C_BOILER_MAN
  fuel_contains: Dung
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
  fuel_contains: Dung
- appliance_contains_all:
  - Medium boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
  fuel_contains: Dung
- appliance_contains_all:
  - Cooking stoves
  - (households)
  class: R_COOKING_STOVE
- appliance_contains_all:
  - Cooking stoves
  - (agr, forestry, other)
  class: R_COOKING_STOVE
- appliance_contains_all:
  - Fireplaces
  - (households)
  class: R_FIREPLACE
- appliance_contains_all:
  - Fireplaces
  - (agr, forestry, other)
  class: R_FIREPLACE
- appliance_contains_all:
  - Heating stoves
  - (households)
  class: R_HEATING_STOVE
- appliance_contains_all:
  - Heating stoves
  - (agr, forestry, other)
  class: R_HEATING_STOVE
- appliance_contains_all:
  - Three-stone stove
  class: R_COOKING_STOVE
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (households)
  class: R_BOILER_AUT
- appliance_contains_all:
  - Single house boilers
  - manual
  - (households)
  class: R_BOILER_MAN
- appliance_contains_all:
  - Single house boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
- appliance_contains_all:
  - Single house boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (commercial)
  class: C_BOILER_AUT
- appliance_contains_all:
  - Medium boilers
  - manual
  - (commercial)
  class: C_BOILER_MAN
- appliance_contains_all:
  - Medium boilers
  - automatic
  - (agr, forestry, other)
  class: R_BOILER_AUT
- appliance_contains_all:
  - Medium boilers
  - manual
  - (agr, forestry, other)
  class: R_BOILER_MAN
