Input_folder: Output/UrbEm/Athens_2019
Output_folder: Output/CityChem/Athens_2019
City: Athens
Year: 2019
EPSG: 32634

domain: # Athens
  xmin: 716397
  ymin: 4191261
  xmax: 761397
  ymax: 4236261

#domain: #Ioannina
#  xmin: 468000
#  ymin: 4375000
#  xmax: 499000
#  ymax: 4406000

#domain: # Kozani
#  xmin: 551000
#  ymin: 4453000
#  xmax: 582000
#  ymax: 4484000

#domain : Athens
Grid_step_m: 1000
Roads_lines:
  path: INPUT/Proxy/ProxySpecific/Roads/spatial_distribution_transport_cams_reg_v8.1_files/em_vkm_vector_dataset.gpkg
  layer: em_osm_europe_21072023_urh_motorway_novo_rossia_crimea_fix_country_scaled
  highway_column: highway
# CAMS GNFR → SNAP (UrbEm folder names on the right)
SNAP_TO_GNFR:
  SNAP_1: A_PublicPower
  SNAP_2: C_OtherCombustion
  SNAP_3: B_Industry
  SNAP_5: D_Fugitive
  SNAP_6: E_Solvents
  SNAP_7: F_Roads
  SNAP_8:
    - G_Shipping
    - H_Aviation
    - I_Offroad
  SNAP_9: J_Waste
  SNAP_10: K_Agriculture
ZCOR_SW:
  SNAP_1: 10
  SNAP_2: 10
  SNAP_3: 10
  SNAP_4: 10
  SNAP_5: 10
  SNAP_6: 0
  SNAP_7: 0
  SNAP_8: 10
  SNAP_9: 10
  SNAP_10: 0
ZCOR_NE: 10
